server:
  port: 8082

spring:
  application:
    name: order-service

# User service configuration for inter-service communication
user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    com.example.orderservice: INFO
    root: INFO
