apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base/user-service
  - ../../base/order-service

commonLabels:
  environment: dev
  managed-by: argocd

# Add replicas patch and labels for dev environment
patches:
  - target:
      kind: Rollout
      name: user-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/metadata/labels/environment
        value: dev
      - op: add
        path: /spec/template/metadata/labels/managed-by
        value: argocd
  - target:
      kind: Rollout
      name: order-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/metadata/labels/environment
        value: dev
      - op: add
        path: /spec/template/metadata/labels/managed-by
        value: argocd
